version: '3.2'

networks:
  clowns-entertainment:
    external: true

services:
  notifier:
    build:
      context: .
      dockerfile: system/docker/notifier/Dockerfile
    container_name: clowns-entartainment-notifier
    networks:
      - clowns-entertainment


  postgresql:
    image: test/postgresql
    build:
      context: .
      dockerfile: system/docker/postgres/Dockerfile
    container_name: clowns-entartainment-postgresql
    command: postgres
    networks:
      - clowns-entertainment